### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ejnnr** [aaronfi/chess-es6.js#1]
I'd love to use this in my project ([web-chess](https://github.com/jupiter24/web-chess)), but I haven't found a license anywhere so I'm not sure under which restrictions chess-es6.js may be used.

If you intend this to be used by other people, you might want to add a license note somewhere.

Thanks in advance!

**Comment by aaronfi** [comment]
Hi, thank you.
I just added a GPLv3 license.

Thanks.

Other issues or ideas, please let me know.

**Comment by ejnnr** [comment]
Awesome, thanks a lot!
