### ISSUE TITLE
Does not npm install

### ISSUE THREAD

**Issue by GeoffreyPlitt** [aaronfi/chess-es6.js#2]
# I have node 4-LTS on Mac OS X

$ npm install --save aaronfi/chess-es6.js
npm ERR! addLocal Could not install /var/folders/27/j0p716dj6xxb3wqj1zf9_zwm0000gn/T/npm-12183-74d19e5d/git-cache-a45346b98a9a/9869b4d27db43aaa58e01c188419ea6e6d426062
npm ERR! addLocal Could not install /var/folders/27/j0p716dj6xxb3wqj1zf9_zwm0000gn/T/npm-12183-74d19e5d/git-cache-76cbad3ab981/9869b4d27db43aaa58e01c188419ea6e6d426062
npm ERR! addLocal Could not install /var/folders/27/j0p716dj6xxb3wqj1zf9_zwm0000gn/T/npm-12183-74d19e5d/git-cache-ba570ef71b6c/9869b4d27db43aaa58e01c188419ea6e6d426062
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.5/bin/node" "/usr/local/bin/npm" "install" "--save" "aaronfi/chess-es6.js"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.4

npm ERR! No version provided in package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by ejnnr** [comment]
The issue seems to be that the `package.json` of chess-es6.js doesn't specify a verison number.
When I added one, everything worked. See #3.
